server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 5

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
